# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Rami's Blog
tagline:             'biomedical engineering - data - urbanism'
description:         'A blog about engineering, health, urbanism and other tidbits'
url:                 rami-codes.github.io
baseurl:             rami-codes.github.io
paginate:            5

# About/contact
author:
  name:              Rami Saab
  url:               ramisaab.me
  email:             ramisaabmail@gmail.com

# Custom vars
version:             1.0.3
