# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               rami-codes
tagline:             'biomedical engineering - data - urbanism.'
description:         'rami-code''s blog on biomedical engineering, data, urbanism and other tidbits'
url:                 rami-codes.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rami Saab
  url:               ramisaab.me
  email:             ramisaabmail@gmail.com
  github:            rami-codes

# Custom vars
version:             1.0.3
markdown:            kramdown
